//! `k2 bindgen` — generate K2 FFI bindings from a C header using libclang.
//!
//! Parses an arbitrary C header into a clang AST, then emits idiomatic K2:
//!   * C functions  → `#extern("<lib>", "<name>") name :: fn(...) -> ...;`
//!   * C structs    → `Name :: struct { ... }`
//!   * C enums      → `pub CONST :: <value>;` (+ a `Name :: i32` alias)
//!   * C typedefs   → `Name :: <type>;` aliases
//!   * `#system_library("<lib>")`
//!
//! The Win64 C ABI lowering in `backend/llvm/abi.zig` is what makes the
//! generated by-value struct signatures actually correct at the call boundary.
//!
//! v1 maps the common scalar/pointer/struct/enum/array shapes. Not yet handled
//! (emitted best-effort, refined later): preprocessor `#define` constants,
//! C unions (emitted as an opaque byte blob of the right size), function-pointer
//! typedefs (mapped to a raw pointer), bitfields, and variadics.

const std = @import("std");
const c = @import("clang_c.zig").c;
const build_options = @import("build_options");
const keywordKind = @import("lexer/tokens.zig").keywordKind;

pub const BindgenError = error{
    ClangNotEnabled,
    ParseFailed,
    WriteFailed,
    OutOfMemory,
};

/// Generate bindings for `header_path` into `out_path`. `lib_name` names the
/// import library for `#extern`/`#system_library` (defaults to the header stem).
/// `clang_args` are passed through to the parser (e.g. `-I`, `-D`).
pub fn generate(
    gpa: std.mem.Allocator,
    io: std.Io,
    header_path: []const u8,
    lib_name: ?[]const u8,
    out_path: []const u8,
    clang_args: []const []const u8,
) !void {
    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const lib = lib_name orelse stem(header_path);
    const index = c.clang_createIndex(0, 0);
    defer c.clang_disposeIndex(index);

    const argv = try buildArgv(arena, clang_args, io);
    const header_z = try arena.dupeZ(u8, header_path);
    const tu = c.clang_parseTranslationUnit(
        index,
        header_z.ptr,
        argv.ptr,
        @intCast(argv.len),
        null,
        0,
        c.CXTranslationUnit_SkipFunctionBodies | c.CXTranslationUnit_DetailedPreprocessingRecord,
    );
    if (tu == null) {
        std.debug.print("k2 bindgen: clang failed to parse '{s}'\n", .{header_path});
        return error.ParseFailed;
    }
    defer c.clang_disposeTranslationUnit(tu);
    reportDiagnostics(tu, header_path);

    const text = try emitModule(arena, tu, lib, header_path);
    std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = text }) catch
        return error.WriteFailed;
    std.debug.print("k2 bindgen: wrote {s} ({d} bytes)\n", .{ out_path, text.len });
}

/// In-memory variant: parse `source` (a virtual header named `header_name`) and
/// return the generated K2 (caller owns the result). No system-include probing —
/// the source should be self-contained. Used for tests and embedding.
pub fn generateString(
    gpa: std.mem.Allocator,
    header_name: []const u8,
    source: []const u8,
    lib_name: ?[]const u8,
    clang_args: []const []const u8,
) ![]u8 {
    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const lib = lib_name orelse stem(header_name);
    const index = c.clang_createIndex(0, 0);
    defer c.clang_disposeIndex(index);

    const argv = try buildArgv(arena, clang_args, null);
    const name_z = try arena.dupeZ(u8, header_name);
    const src_z = try arena.dupeZ(u8, source);
    var unsaved = c.CXUnsavedFile{
        .Filename = name_z.ptr,
        .Contents = src_z.ptr,
        .Length = @intCast(source.len),
    };
    const tu = c.clang_parseTranslationUnit(
        index,
        name_z.ptr,
        argv.ptr,
        @intCast(argv.len),
        &unsaved,
        1,
        c.CXTranslationUnit_SkipFunctionBodies | c.CXTranslationUnit_DetailedPreprocessingRecord,
    );
    if (tu == null) return error.ParseFailed;
    defer c.clang_disposeTranslationUnit(tu);

    const text = try emitModule(arena, tu, lib, header_name);
    return gpa.dupe(u8, text);
}

/// Default clang command line: Win64 target, C input, the SDK's builtin-header
/// dir (only when `io` is given), then the caller's `-I`/`-D`/etc.
fn buildArgv(arena: std.mem.Allocator, clang_args: []const []const u8, io: ?std.Io) ![]const [*c]const u8 {
    var argv: std.ArrayList([*c]const u8) = .empty;
    try argv.append(arena, "-x");
    try argv.append(arena, "c");
    try argv.append(arena, "-target");
    try argv.append(arena, "x86_64-pc-windows-msvc");
    // libclang loaded as a DLL doesn't auto-locate its builtin headers
    // (stddef.h/stdint.h/…). Point it at the SDK's clang resource include dir.
    if (io) |the_io| if (clangResourceInclude(arena, the_io)) |inc| {
        try argv.append(arena, "-isystem");
        try argv.append(arena, (try arena.dupeZ(u8, inc)).ptr);
    };
    for (clang_args) |a| try argv.append(arena, (try arena.dupeZ(u8, a)).ptr);
    return argv.items;
}

/// Walk a parsed translation unit and emit the K2 module text (arena-owned).
fn emitModule(arena: std.mem.Allocator, tu: c.CXTranslationUnit, lib: []const u8, label: []const u8) ![]u8 {
    var gen = Generator{
        .arena = arena,
        .tu = tu,
        .lib = lib,
        .out = .empty,
        .emitted = std.StringHashMap(void).init(arena),
        .referenced = std.StringHashMap(void).init(arena),
    };
    try gen.out.print(arena,
        \\// Generated by `k2 bindgen` from {s}. Do not edit by hand.
        \\
        \\#system_library("{s}");
        \\
        \\
    , .{ label, lib });

    const root = c.clang_getTranslationUnitCursor(tu);
    const decls = try directChildren(arena, root);
    for (decls) |cursor| {
        // Skip declarations pulled in from system headers — keep the output to
        // the target header's own surface.
        if (c.clang_Location_isInSystemHeader(c.clang_getCursorLocation(cursor)) != 0) continue;
        try gen.emitDecl(cursor);
    }

    // Any type referenced but never defined (opaque C handles, forward decls) is
    // emitted as an `opaque` type so every `*Name` use resolves.
    var ref_it = gen.referenced.keyIterator();
    var first_opaque = true;
    while (ref_it.next()) |k| {
        if (gen.emitted.contains(k.*)) continue;
        if (first_opaque) {
            try gen.out.appendSlice(arena, "// opaque / forward-declared types (used only by pointer)\n");
            first_opaque = false;
        }
        try gen.out.print(arena, "pub {s} :: opaque;\n", .{try gen.ident(k.*)});
    }
    return gen.out.items;
}

const Generator = struct {
    arena: std.mem.Allocator,
    tu: c.CXTranslationUnit,
    lib: []const u8,
    out: std.ArrayList(u8),
    /// Names already emitted, so a struct and its same-named typedef don't clash.
    emitted: std.StringHashMap(void),
    /// Named types referenced as a type somewhere. Any that are never defined
    /// (forward-declared / opaque C handles) get a trailing `Name :: opaque;` so
    /// the generated module always compiles.
    referenced: std.StringHashMap(void),

    /// A C identifier rendered as a valid K2 identifier: names that collide with
    /// a K2 keyword (`type`, `match`, `in`, `fn`, …) get a trailing `_`. Applied
    /// at every definition and reference site so the renames stay consistent.
    fn ident(self: *Generator, name: []const u8) ![]const u8 {
        if (name.len != 0 and keywordKind(name) != .ident)
            return std.fmt.allocPrint(self.arena, "{s}_", .{name});
        return name;
    }

    fn markEmitted(self: *Generator, name: []const u8) !bool {
        if (name.len == 0) return true; // anonymous — caller decides
        if (self.emitted.contains(name)) return true;
        try self.emitted.put(name, {});
        return false;
    }

    fn emitDecl(self: *Generator, cursor: c.CXCursor) !void {
        switch (c.clang_getCursorKind(cursor)) {
            c.CXCursor_FunctionDecl => try self.emitFunction(cursor),
            c.CXCursor_StructDecl, c.CXCursor_UnionDecl => {
                if (c.clang_isCursorDefinition(cursor) != 0)
                    try self.emitRecord(cursor, spelling(self.arena, cursor) catch return);
            },
            c.CXCursor_EnumDecl => try self.emitEnum(cursor),
            c.CXCursor_TypedefDecl => try self.emitTypedef(cursor),
            c.CXCursor_MacroDefinition => try self.emitMacro(cursor),
            else => {},
        }
    }

    /// Object-like `#define` constants. Three shapes are recognized; everything
    /// else (function-like macros, expression macros) is skipped:
    ///   * a single numeric/string literal     → `pub NAME :: <literal>;`
    ///   * `[CLITERAL](Type){ v, ... }` (raylib colors like `RAYWHITE`)
    ///                                          → a `#run`-folded typed constant
    fn emitMacro(self: *Generator, cursor: c.CXCursor) !void {
        if (c.clang_Cursor_isMacroFunctionLike(cursor) != 0) return;
        if (c.clang_Cursor_isMacroBuiltin(cursor) != 0) return;

        const name = try spelling(self.arena, cursor);
        if (name.len == 0 or std.mem.startsWith(u8, name, "_")) return; // skip guards/internal
        if (self.emitted.contains(name)) return;

        const body = try self.macroBody(cursor, name);
        if (body.len == 0) return;

        // Compound literal: optional `CLITERAL`, then `( Type ) { values }`.
        if (try self.matchCompoundLiteral(body)) |lit| {
            if (try self.markEmitted(name)) return;
            const k2name = try self.ident(name);
            try self.out.print(self.arena,
                \\__lit_{s} :: fn() -> {s} {{ return .{{ {s} }}; }}
                \\pub {s} :: #run __lit_{s}();
                \\
                \\
            , .{ k2name, try self.ident(lit.type_name), lit.values, k2name, k2name });
            return;
        }

        // A single literal token (number or string).
        if (body.len == 1 and (body[0].kind == .literal)) {
            const lit = cleanLiteral(body[0].text) orelse return;
            if (try self.markEmitted(name)) return;
            try self.out.print(self.arena, "pub {s} :: {s};\n\n", .{ try self.ident(name), lit });
            return;
        }
    }

    /// Tokenize a macro definition and return its body tokens (everything after
    /// the macro name), dropping libclang's spurious trailing token via a source
    /// offset filter.
    fn macroBody(self: *Generator, cursor: c.CXCursor, name: []const u8) ![]const Tok {
        const range = c.clang_getCursorExtent(cursor);
        var end_off: c_uint = 0;
        c.clang_getFileLocation(c.clang_getRangeEnd(range), null, null, null, &end_off);

        var toks: [*c]c.CXToken = undefined;
        var n: c_uint = 0;
        c.clang_tokenize(self.tu, range, &toks, &n);
        defer c.clang_disposeTokens(self.tu, toks, n);

        var out: std.ArrayList(Tok) = .empty;
        var seen_name = false;
        var i: c_uint = 0;
        while (i < n) : (i += 1) {
            const t = toks[i];
            var off: c_uint = 0;
            c.clang_getFileLocation(c.clang_getTokenLocation(self.tu, t), null, null, null, &off);
            if (off >= end_off) continue; // libclang off-by-one: drop trailing token
            const text = try cxString(self.arena, c.clang_getTokenSpelling(self.tu, t));
            if (!seen_name) {
                if (std.mem.eql(u8, text, name)) seen_name = true;
                continue; // skip up to and including the macro name
            }
            try out.append(self.arena, .{ .kind = tokKind(c.clang_getTokenKind(t)), .text = text });
        }
        return out.items;
    }

    /// Match `[CLITERAL] ( Type ) { v, v, ... }` (C compound literal) and return
    /// the type name + the values joined as text. Trailing tokens after `}` are
    /// ignored. Returns null if the body isn't a compound literal.
    fn matchCompoundLiteral(self: *Generator, body: []const Tok) !?CompoundLit {
        var i: usize = 0;
        while (i < body.len and !(body[i].kind == .punct and std.mem.eql(u8, body[i].text, "("))) : (i += 1) {}
        if (i + 3 >= body.len) return null;
        if (body[i + 1].kind != .identifier) return null;
        const type_name = body[i + 1].text;
        if (!(body[i + 2].kind == .punct and std.mem.eql(u8, body[i + 2].text, ")"))) return null;
        if (!(body[i + 3].kind == .punct and std.mem.eql(u8, body[i + 3].text, "{"))) return null;

        var vals: std.ArrayList(u8) = .empty;
        var j = i + 4;
        while (j < body.len and !(body[j].kind == .punct and std.mem.eql(u8, body[j].text, "}"))) : (j += 1) {
            if (vals.items.len != 0) try vals.append(self.arena, ' ');
            try vals.appendSlice(self.arena, body[j].text);
        }
        if (j >= body.len) return null; // no closing brace
        if (vals.items.len == 0) return null;
        return CompoundLit{ .type_name = type_name, .values = vals.items };
    }

    fn emitFunction(self: *Generator, cursor: c.CXCursor) !void {
        const name = try spelling(self.arena, cursor);
        if (try self.markEmitted(name)) return;

        var params: std.ArrayList(u8) = .empty;
        const n = c.clang_Cursor_getNumArguments(cursor);
        var i: c_int = 0;
        while (i < n) : (i += 1) {
            const arg = c.clang_Cursor_getArgument(cursor, @intCast(i));
            const pname = try spelling(self.arena, arg);
            const pty = try self.mapType(c.clang_getCursorType(arg));
            if (i != 0) try params.appendSlice(self.arena, ", ");
            if (pname.len != 0)
                try params.print(self.arena, "{s}: {s}", .{ try self.ident(pname), pty })
            else
                try params.print(self.arena, "arg{d}: {s}", .{ i, pty });
        }

        const ret = c.clang_getCursorResultType(cursor);
        const ret_str = try self.mapType(ret);
        const ret_clause = if (std.mem.eql(u8, ret_str, "void"))
            ""
        else
            try std.fmt.allocPrint(self.arena, " -> {s}", .{ret_str});

        // C variadics aren't representable; bind the fixed parameters and flag it.
        if (c.clang_isFunctionTypeVariadic(c.clang_getCursorType(cursor)) != 0)
            try self.out.appendSlice(self.arena, "// note: C variadic function — only the fixed parameters are bound\n");

        try self.out.print(self.arena,
            \\#extern("{s}", "{s}")
            \\pub {s} :: fn({s}){s};
            \\
            \\
        , .{ self.lib, name, try self.ident(name), params.items, ret_clause });
    }

    fn emitRecord(self: *Generator, cursor: c.CXCursor, name: []const u8) !void {
        if (name.len == 0) return;

        const fields = try directChildren(self.arena, cursor);

        // Unions and bitfield structs can't be field-mapped without breaking the
        // ABI (overlapping / packed storage). Emit a size+align-correct opaque
        // blob instead, so by-value passing stays correct (poke via casts).
        const is_union = c.clang_getCursorKind(cursor) == c.CXCursor_UnionDecl;
        var has_bitfield = false;
        for (fields) |f| {
            if (c.clang_getCursorKind(f) == c.CXCursor_FieldDecl and c.clang_Cursor_isBitField(f) != 0) {
                has_bitfield = true;
                break;
            }
        }
        if (is_union or has_bitfield)
            return self.emitSizedBlob(name, c.clang_getCursorType(cursor), if (is_union) "C union" else "C struct with bitfields");

        if (try self.markEmitted(name)) return;
        try self.out.print(self.arena, "pub {s} :: struct {{\n", .{try self.ident(name)});
        var any = false;
        for (fields) |f| {
            if (c.clang_getCursorKind(f) != c.CXCursor_FieldDecl) continue;
            const fname = try spelling(self.arena, f);
            const fty = try self.mapType(c.clang_getCursorType(f));
            try self.out.print(self.arena, "    {s}: {s},\n", .{ try self.ident(fname), fty });
            any = true;
        }
        if (!any) try self.out.appendSlice(self.arena, "    _unused: u8,\n");
        try self.out.appendSlice(self.arena, "}\n\n");
    }

    /// A size+alignment-correct opaque byte blob (for unions, bitfield structs,
    /// and anything whose fields we can't faithfully map).
    fn emitSizedBlob(self: *Generator, name: []const u8, ty: c.CXType, why: []const u8) !void {
        if (name.len == 0) return;
        if (try self.markEmitted(name)) return;
        const sz = c.clang_Type_getSizeOf(ty);
        if (sz <= 0) { // incomplete — fall back to an opaque type
            try self.out.print(self.arena, "pub {s} :: opaque;\n\n", .{try self.ident(name)});
            return;
        }
        try self.out.print(self.arena, "// {s} — opaque storage ({d} bytes); access via casts\n", .{ why, sz });
        const al = c.clang_Type_getAlignOf(ty);
        if (al > 1) try self.out.print(self.arena, "#align({d})\n", .{al});
        try self.out.print(self.arena, "pub {s} :: struct {{ _bytes: [{d}]u8 }}\n\n", .{ try self.ident(name), sz });
    }

    fn emitEnum(self: *Generator, cursor: c.CXCursor) !void {
        const name = try spelling(self.arena, cursor);
        // C enum constants are global integer constants — emit them as such.
        const consts = try directChildren(self.arena, cursor);
        var any = false;
        for (consts) |k| {
            if (c.clang_getCursorKind(k) != c.CXCursor_EnumConstantDecl) continue;
            const cname = try spelling(self.arena, k);
            if (try self.markEmitted(cname)) continue;
            const val = c.clang_getEnumConstantDeclValue(k);
            try self.out.print(self.arena, "pub {s} :: {d};\n", .{ try self.ident(cname), val });
            any = true;
        }
        if (any) try self.out.appendSlice(self.arena, "\n");
        // A named enum is used as a (C int) type — alias it so params resolve.
        if (name.len != 0 and !(try self.markEmitted(name)))
            try self.out.print(self.arena, "pub {s} :: i32;\n\n", .{try self.ident(name)});
    }

    fn emitTypedef(self: *Generator, cursor: c.CXCursor) !void {
        const name = try spelling(self.arena, cursor);
        if (self.emitted.contains(name)) return;

        const under = c.clang_getTypedefDeclUnderlyingType(cursor);
        const canon = c.clang_getCanonicalType(under);
        switch (canon.kind) {
            // typedef struct {...} Name;  → emit the struct under the typedef name.
            c.CXType_Record => try self.emitRecord(c.clang_getTypeDeclaration(canon), name),
            // typedef enum {...} Name;    → already handled by the EnumDecl; alias the type.
            c.CXType_Enum => {
                if (!(try self.markEmitted(name)))
                    try self.out.print(self.arena, "pub {s} :: i32;\n\n", .{try self.ident(name)});
            },
            else => {
                if (try self.markEmitted(name)) return;
                // A function-pointer typedef can't be a K2 type alias
                // (`Name :: fn(...)` parses as a function decl), so it's expanded
                // inline at use sites — emit only a note here.
                if (canon.kind == c.CXType_Pointer) {
                    const pk = c.clang_getPointeeType(canon).kind;
                    if (pk == c.CXType_FunctionProto or pk == c.CXType_FunctionNoProto) {
                        try self.out.print(self.arena, "// {s}: C function pointer (expanded inline at use sites)\n\n", .{name});
                        return;
                    }
                }
                const mapped = try self.mapType(under);
                try self.out.print(self.arena, "pub {s} :: {s};\n\n", .{ try self.ident(name), mapped });
            },
        }
    }

    // ── C type → K2 type ────────────────────────────────────────────────────

    fn mapType(self: *Generator, ty: c.CXType) BindgenError![]const u8 {
        return switch (ty.kind) {
            c.CXType_Void => "void",
            c.CXType_Bool => "bool",
            c.CXType_Char_S, c.CXType_SChar => "i8",
            c.CXType_Char_U, c.CXType_UChar => "u8",
            c.CXType_Short => "i16",
            c.CXType_UShort => "u16",
            c.CXType_Int => "i32",
            c.CXType_UInt => "u32",
            c.CXType_Long => "i32", // LLP64: long is 32-bit on Windows
            c.CXType_ULong => "u32",
            c.CXType_LongLong => "i64",
            c.CXType_ULongLong => "u64",
            c.CXType_Float => "f32",
            c.CXType_Double => "f64",
            c.CXType_LongDouble => "f64", // Win64: long double == double (8 bytes)
            c.CXType_Pointer => try self.mapPointer(ty),
            c.CXType_ConstantArray => try std.fmt.allocPrint(self.arena, "[{d}]{s}", .{
                c.clang_getArraySize(ty),
                try self.mapType(c.clang_getArrayElementType(ty)),
            }),
            c.CXType_IncompleteArray => try std.fmt.allocPrint(self.arena, "[*]{s}", .{
                try self.mapType(c.clang_getArrayElementType(ty)),
            }),
            c.CXType_Record, c.CXType_Enum, c.CXType_Elaborated => try self.namedType(ty),
            c.CXType_Typedef => blk: {
                // A typedef to a struct/enum keeps the name; a scalar typedef
                // (size_t, int32_t, …) resolves to its canonical primitive.
                const canon = c.clang_getCanonicalType(ty);
                break :blk switch (canon.kind) {
                    c.CXType_Record, c.CXType_Enum => try self.namedType(ty),
                    else => try self.mapType(canon),
                };
            },
            c.CXType_FunctionProto, c.CXType_FunctionNoProto => try self.mapFnType(ty),
            else => "usize", // opaque fallback (keeps pointer-sized ABI)
        };
    }

    /// A C function type → K2's inline function-pointer type `fn(args) -> ret`.
    /// (K2 has no `Name :: fn(...)` type-alias syntax, so callbacks are always
    /// expanded inline at their use site.)
    fn mapFnType(self: *Generator, fnproto: c.CXType) BindgenError![]const u8 {
        var buf: std.ArrayList(u8) = .empty;
        try buf.appendSlice(self.arena, "fn(");
        const nargs = @max(c.clang_getNumArgTypes(fnproto), 0);
        var i: c_int = 0;
        while (i < nargs) : (i += 1) {
            if (i != 0) try buf.appendSlice(self.arena, ", ");
            try buf.appendSlice(self.arena, try self.mapType(c.clang_getArgType(fnproto, @intCast(i))));
        }
        try buf.appendSlice(self.arena, ") -> ");
        try buf.appendSlice(self.arena, try self.mapType(c.clang_getResultType(fnproto)));
        return buf.items;
    }

    fn mapPointer(self: *Generator, ty: c.CXType) BindgenError![]const u8 {
        const pointee = c.clang_getPointeeType(ty);
        const is_const = c.clang_isConstQualifiedType(pointee) != 0;
        return switch (pointee.kind) {
            c.CXType_Void => "*opaque",
            c.CXType_Char_S, c.CXType_Char_U, c.CXType_SChar, c.CXType_UChar =>
                if (is_const) "[*]const u8" else "[*]u8",
            c.CXType_FunctionProto, c.CXType_FunctionNoProto => try self.mapFnType(pointee),
            else => blk: {
                const inner = try self.mapType(pointee);
                break :blk try std.fmt.allocPrint(self.arena, "{s}{s}", .{
                    if (is_const) "*const " else "*",
                    inner,
                });
            },
        };
    }

    /// Clean name of a record/enum/typedef type (its declaration's spelling).
    fn namedType(self: *Generator, ty: c.CXType) BindgenError![]const u8 {
        const decl = c.clang_getTypeDeclaration(ty);
        const name = spelling(self.arena, decl) catch return error.OutOfMemory;
        if (name.len == 0) return "usize"; // anonymous type used inline — fallback
        self.referenced.put(name, {}) catch {};
        return self.ident(name);
    }
};

// ── macro token helpers ─────────────────────────────────────────────────────

const TokKind = enum { literal, identifier, punct, keyword, other };
const Tok = struct { kind: TokKind, text: []const u8 };
const CompoundLit = struct { type_name: []const u8, values: []const u8 };

fn tokKind(k: c.CXTokenKind) TokKind {
    return switch (k) {
        c.CXToken_Literal => .literal,
        c.CXToken_Identifier => .identifier,
        c.CXToken_Punctuation => .punct,
        c.CXToken_Keyword => .keyword,
        else => .other,
    };
}

/// Render a C numeric/string literal token as a K2 literal, or null if it isn't
/// one K2 can take verbatim (char literals, etc.). Strips C integer/float
/// suffixes (`u`, `L`, `f`, …) but preserves hex digits.
fn cleanLiteral(text: []const u8) ?[]const u8 {
    if (text.len == 0) return null;
    if (text[0] == '"') return text; // string literal — valid K2 as-is
    if (text[0] == '\'') return null; // char literal — skip
    const is_hex = text.len >= 2 and text[0] == '0' and (text[1] == 'x' or text[1] == 'X');
    var end = text.len;
    while (end > 0) {
        const ch = text[end - 1];
        const suffix = ch == 'u' or ch == 'U' or ch == 'l' or ch == 'L' or
            (!is_hex and (ch == 'f' or ch == 'F'));
        if (suffix) end -= 1 else break;
    }
    if (end == 0) return null;
    const s = text[0..end];
    if (!((s[0] >= '0' and s[0] <= '9') or s[0] == '.')) return null;
    return s;
}

// ── libclang helpers ────────────────────────────────────────────────────────

/// A cursor's spelling, duped into `arena`.
fn spelling(arena: std.mem.Allocator, cursor: c.CXCursor) ![]const u8 {
    return cxString(arena, c.clang_getCursorSpelling(cursor));
}

/// Copy a CXString into `arena` and dispose the original.
fn cxString(arena: std.mem.Allocator, cxstr: c.CXString) ![]const u8 {
    defer c.clang_disposeString(cxstr);
    const ptr = c.clang_getCString(cxstr) orelse return "";
    return arena.dupe(u8, std.mem.span(ptr));
}

const Collector = struct {
    gpa: std.mem.Allocator,
    list: std.ArrayList(c.CXCursor) = .empty,
    oom: bool = false,
};

fn visitCollect(cursor: c.CXCursor, parent: c.CXCursor, data: c.CXClientData) callconv(.c) c.CXChildVisitResult {
    _ = parent;
    const col: *Collector = @ptrCast(@alignCast(data));
    col.list.append(col.gpa, cursor) catch {
        col.oom = true;
        return c.CXChildVisit_Break;
    };
    return c.CXChildVisit_Continue;
}

/// The direct children of `cursor` (one level, no recursion).
fn directChildren(gpa: std.mem.Allocator, cursor: c.CXCursor) ![]c.CXCursor {
    var col = Collector{ .gpa = gpa };
    _ = c.clang_visitChildren(cursor, visitCollect, &col);
    if (col.oom) return error.OutOfMemory;
    return col.list.toOwnedSlice(gpa);
}

/// Print clang's own parse diagnostics (errors/warnings) to stderr.
fn reportDiagnostics(tu: c.CXTranslationUnit, header_path: []const u8) void {
    const n = c.clang_getNumDiagnostics(tu);
    if (n == 0) return;
    var i: c_uint = 0;
    var errors: u32 = 0;
    while (i < n) : (i += 1) {
        const diag = c.clang_getDiagnostic(tu, i);
        defer c.clang_disposeDiagnostic(diag);
        const sev = c.clang_getDiagnosticSeverity(diag);
        if (sev < c.CXDiagnostic_Error) continue; // only surface errors
        errors += 1;
        const cxs = c.clang_formatDiagnostic(diag, c.clang_defaultDiagnosticDisplayOptions());
        defer c.clang_disposeString(cxs);
        if (c.clang_getCString(cxs)) |s|
            std.debug.print("k2 bindgen: {s}\n", .{std.mem.span(s)});
    }
    if (errors != 0)
        std.debug.print("k2 bindgen: {s} parsed with {d} clang error(s); bindings may be incomplete\n", .{ header_path, errors });
}

/// Discover the clang builtin-header directory shipped with the SDK
/// (`<llvm>/lib/clang/<version>/include`), so libclang can find stddef.h etc.
/// Best-effort: returns null if it can't be located (clang then errors on the
/// missing system headers, but non-dependent declarations still come through).
fn clangResourceInclude(arena: std.mem.Allocator, io: std.Io) ?[]const u8 {
    const llvm_path = build_options.llvm_path;
    if (llvm_path.len == 0) return null;
    // Probe descending clang major versions for `<llvm>/lib/clang/<v>/include`,
    // confirming it by reading the stddef.h that lives there.
    var v: u32 = 30;
    while (v >= 10) : (v -= 1) {
        const probe = std.fmt.allocPrint(arena, "{s}/lib/clang/{d}/include/stddef.h", .{ llvm_path, v }) catch return null;
        const data = std.Io.Dir.cwd().readFileAlloc(io, probe, arena, .unlimited) catch continue;
        arena.free(data);
        return std.fmt.allocPrint(arena, "{s}/lib/clang/{d}/include", .{ llvm_path, v }) catch return null;
    }
    return null;
}

/// The file stem of a path (no directory, no extension), for a default lib name.
fn stem(path: []const u8) []const u8 {
    const base = std.fs.path.basename(path);
    const dot = std.mem.lastIndexOfScalar(u8, base, '.') orelse return base;
    return if (dot == 0) base else base[0..dot];
}
